### ISSUE TITLE
Building on Mac OS 10.9.4

### ISSUE THREAD

**Issue by royalstream** [dmlc/mshadow#10]
I managed to build **cxxnet+mshadow** on Mac OS X 10.9.4 after doing several changes to the Makefile (which I can share if anyone's interested) mostly to deal with the well known libc++/libstdc++ issue in Mavericks.
Clang gave me several harmless warning about types being declared as structs and defined as classes (or the other way around). However, it was also failing to compile and I had to change line 453 in **tensor.h** because it looks like it was missing the dimkeep parameter and Clang was unforgiving about it:

``` C++
template<typename Saver, typename Reducer, int dimkeep, typename E, int etype>
```

I'm new to mshadow/cxxnet (I discovered it yesterday evening) so I apologize beforehand if my contribution is not correct.

Regards,

Steven

**Comment by tqchen** [comment]
Your observation is correctly and this is indeed what we overlooked. Thanks!

**Comment by tqchen** [comment]
I have changed the code in the master branch to reflect your fix. It would be great if you like to share the Makefile in MAC. They are usually in make folder.

Tianqi

**Comment by pchankh** [comment]
Hi Steven, 
I am having linker issues on trying to compile cxxnet+mshadow on Mac OSX 10.9.4
with CUDA 6.5 and MKL installed.
Could you share your approach?
Thanks
Patrick
