### ISSUE TITLE
[Discussion] Support sort in mshadow?

### ISSUE THREAD

**Issue by antinucleon** [dmlc/mshadow#118]
Do we need to do this? For CPU we can use std::sort, for GPU we can refer CUDA examples.

sampe_api

```
dst, idx = sort(src)
```

where idx is the `argsort` result

**Comment by tqchen** [comment]
if there is need for this, we can try to add a support.

**Comment by antinucleon** [comment]
The use case is very rare for now. What I know is:
1. nms
2. strange gates layer with some "experts"  (doesn't work for 3 years research).

**Comment by tqchen** [comment]
then i will bring them as mxnet operator level first, before bring them into mshadow

**Comment by antinucleon** [comment]
LGTM
