### ISSUE TITLE
Initialization on GPU slow ( turns out that my cuda is broken)

### ISSUE THREAD

**Issue by huashiyiqike** [dmlc/mshadow#12]
The cublasInit() call is very time consuming, which is not trivial in debugging. Is there a possibility to circumvent using this function in your implementation? I have used CAFFE which seems to be very fast in GPU initialization.

**Comment by tqchen** [comment]
currently we do need cublasInit() to use cuBLAS library.  
Though seems some cuda kernel doesn't really need this Initialization function( I am not completely sure), and skiping initalization also makes things work
