### ISSUE TITLE
Multiple GPU support

### ISSUE THREAD

**Issue by huashiyiqike** [dmlc/mshadow#14]
I do not know if mshadow could support multiple GPU now.  
Instead  of pre-define the id of device, it could also be templated ( with a default device number) to enable Tensor on multiple GPUs.

**Comment by tqchen** [comment]
I am not sure how much change is needed for multiGPU CUDA kernel vs single GPU cuda kernel. Some hacks may be needed

**Comment by huashiyiqike** [comment]
The existing approaches seem to be multi-threading, with datum and calculations in different devices in parallel. For Mshadow, device in Tensor< Device, dim > may be set according to targeted device.  Maybe this can be straightforward?

**Comment by tqchen** [comment]
I am thinking about this, this could need some effort, but I guess is possible.

**Comment by tqchen** [comment]
Multiple GPU support in refactor branch. This is done with a parameter server interface https://github.com/tqchen/mshadow/blob/refactor/mshadow-ps/ps.h

The new version of cxxnet will come with this interface and being able to efficiently sync between different GPUs.
