### ISSUE TITLE
How to safely free the space of the Tensor

### ISSUE THREAD

**Issue by zhangmeishan** [dmlc/mshadow#144]
When I do not know whether t has been allocated, how I free?
if (t.dptr_ != NULL)  FreeSpace(&t)
or
if(t.stream_ != NULL) FreeSpace(&t)
Anyone correct or some other method?
Thanks.

**Comment by antinucleon** [comment]
Use tensor container instead of raw tensor

**Comment by zhangmeishan** [comment]
If raw tensor is required? So how?

**Comment by zhangmeishan** [comment]
I think that "if (t.dptr_ != NULL) FreeSpace(&t)" is better, but I should assign default NULL value for dptr_  in the construct function of Tensor.

**Comment by tqchen** [comment]
yes, you are right
