### ISSUE TITLE
precision issue

### ISSUE THREAD

**Issue by huashiyiqike** [dmlc/mshadow#16]
The operations defined with Map need float precision, otherwise it won't compile, is there a way to use double precision as input (for gradient checking etc)?  For GPU card with  Compute Capability 2.0  or above double precision is supported.  (http://developer.download.nvidia.com/compute/cuda/4_1/rel/toolkit/docs/online/group__CUDA__MATH__DOUBLE.html) 
By the way, I started working on MPI for multiple GPU with mshadow, hope this can work.

**Comment by tqchen** [comment]
mshadow can switch to double precision, by changing the definition of real_t. https://github.com/tqchen/mshadow/blob/master/mshadow/tensor_base.h#L54

The reason why single precision is default.

**Comment by tqchen** [comment]
I would love to hear more about your experience in working with MPI:)

The IStream interface  https://github.com/tqchen/mshadow/blob/master/mshadow/tensor_io.h#L18 could be helpful. In principle, if it is socket connection, you can implement a SocketStream to support Read and Write, then mshadow's SaveBinary/LoadBinary can automatically take that and do read/write over sockets. 

I have little experience with MPI, so I am not sure if this idea can be used there as well

**Comment by huashiyiqike** [comment]
I have set real_t, the problem is the input in Map has to be truncated to float（cannot be real_t now), even the inner can return a double by changing expf to exp, as follows:

```
struct sigmoid {
            MSHADOW_XINLINE static real_t Map(float a){
                return 1.0 / (1.0 + exp(-a));
            }
    };
```

otherwise：
./mshadow/mshadow/cuda/tensor_gpu-inl.cuh(59): error: expression preceding parentheses of apparent call must have (pointer-to-) function type

Thank you for your advice, MPI is my course project, I will put much effort into it, just haven't started yet.
