### ISSUE TITLE
error: conflicting declaration ‘typedef int cudnnTensorFormat_t’

### ISSUE THREAD

**Issue by yuewu001** [dmlc/mshadow#188]
cudnnTensorFormat_t is already defined in cudnn-v4, the following declaration leads to compilation error
MSHADOW_USE_CUDA && MSHADOW_USE_CUDNN == 1 && CUDNN_MAJOR >= 5

**Comment by yajiedesign** [comment]
wait merge https://github.com/dmlc/mshadow/pull/183
