### ISSUE TITLE
3D Tensor  operations?

### ISSUE THREAD

**Issue by Kublai-Jing** [dmlc/mshadow#20]
Is there operation for 3D tensor( Tensor<cpu,3>) ?

For instance I would like to take one 2D tensor and dot product with the first two dimensions of a 3D tensor: 
Tensor<cpu,2> 2d_ten(Shape2(100,50));
Tensor<cpu,3> 3d_ten(Shape3(50,30,20));

someop(2d_ten, 3d_ten);

I would like to get the result which is a 3D Tensor with shape = (100,30,20)

Thanks.

**Comment by tqchen** [comment]
there won't be such op for dot product, but you can do all the elementwise operations

**Comment by Kublai-Jing** [comment]
but both operands have to be 3D tensor for elemwise-ops to work, right ?

**Comment by tqchen** [comment]
Yes, you are right. However, it is not hard to support some kind of explicit broadcast operations if it is important. For example, you can now use repmat(vec, n) and broadcast<dim>(vec, shape) to broadcast a 1D tensor to any dimension

**Comment by Kublai-Jing** [comment]
Thanks!

**Comment by Kublai-Jing** [comment]
one followed-up question. Is there a way to do smart indexing ?
 say I want to pull out the elements of [0,1,4,7,10] of a Tensor<cpu,2> t2d(Shape2(100,2));
t2d.Slice() seems to be only applicable when index is continuous.

**Comment by tqchen** [comment]
It is very hard and inefficient to do it in GPU, for arbitrary index. 
If your index have a pattern, for example, take every odd index , it is possible to do that

**Comment by bobye** [comment]
@tqchen How to work around if I need some simple slice() operations using ranges, like a[1..10].

**Comment by tqchen** [comment]
I think we have the top level slice operation, which is called Slice
