### ISSUE TITLE
cpu pending

### ISSUE THREAD

**Issue by ziqilau** [dmlc/mshadow#21]
After around 8 hours running, the cpu could idle.

**Comment by ziqilau** [comment]
Sorry, some details are:

It can be run on very small case like: 10_10_20 tensor on 1st layer, 20*10 tensor on 2 layer, which takes about 2 hours. It works good in this case.

But the issue happens when I am setting 40_100_200 tensor on 1st layer, 20*10 tensor on 2 layer. The cpu will idle after about 8~9 hours running.

the total data instances number is around 100M.

thanks.

**Comment by tqchen** [comment]
I have no idea about why such problem will happen. Do you have particular code that you are running. There is no locking in mshadow so far so this should not cause the code to block

**Comment by ziqilau** [comment]
The problem seems come from mkl. It's ok after I switch to openblas.
