### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by rustandruin** [dmlc/mshadow#3]
The rule for $(BIN) is incorrect in the Makefile: the order of -o and LDFLAGS needs to be reversed, otherwise you get an error about unresolved symbols. That is, the target should be `$(CXX) $(CFLAGS) -o $@ $(filter %.cpp %.o %.c, $^) $(LDFLAGS)`

**Comment by tqchen** [comment]
Thanks for pointing this out, we have changed the files.
