### ISSUE TITLE
question about reshape a tensor

### ISSUE THREAD

**Issue by yanqingmen** [dmlc/mshadow#32]
hi, 

I've got some problem when I try to reshape a mat from (1,2) to (2,1) , my code is something like this:

```
Tensor<cpu, 2> mat1 = NewTensor<cpu, float>(Shape2(1,2), 1.0);
//reshape mat from 1*2  to 2*1
Tensor<cpu, 2> mat2(Shape2(2,1));
mat2 = reshape(mat1, mat2.shape_);
```

I got segmentation falt while doing this. I think it's because I didn't allocate memory for mat2, but in my understanding, reshape operation need no extra memory for handling data since mat2 just share data with mat1. I wonder if its my misunderstanding or just because I've done something wrong.

thanks a lot.

**Comment by tqchen** [comment]
You need to allocate the space of mat2 beforehand. Tensor is a memory place handle(ptr) that do not allocate space. You can use TensorContainer for STL style allocation
In mshadow we minimize the space allocation by asking user to explicitly manage space for efficiency reason

**Comment by yanqingmen** [comment]
hi, tqchen.

thanks a lot for your reply. I'll try TensorContainer.
