### ISSUE TITLE
Question about operator= for Tensor and TensorContainer

### ISSUE THREAD

**Issue by superzrx** [dmlc/mshadow#33]
Hi ,
    I`m confused with operator= for Tensor and TensorContainer
    Could someone explain how it works?
    Many thanks :D

``` c++
#include<mshadow/tensor.h>
#include<iostream>
#include<mshadow/tensor_container.h>
void TestTensor(){
  using namespace std;
  using namespace mshadow;
  TensorContainer<cpu, 3> tc3;
  TensorContainer<cpu, 2> tc2;
  tc3.Resize(Shape3(3, 2, 2));
  tc2.Resize(Shape2(2, 2));
  tc2[0][0] = 0; tc2[0][1] = 0.1;
  tc2[1][0] = 1.0; tc2[1][1] = 1.1;
  for (index_t i = 0; i < 3; i++){
    //tc3[i] = tc2; //in this case , failed
    Copy(tc3[i], tc2, tc3.stream_);//succeed
  }
  for (index_t i = 0; i < 3; i++){
    cout << "channel 0" << endl;
    for (index_t j = 0; j < 2; j++)
    {
      for (index_t k = 0; k < 2; k++)
      {
        cout << tc3[i][j][k] << " ";
      }
    }
    cout << endl;
  }
}
```

![0sjl8g3 oy3 lvq0p4fsif](https://cloud.githubusercontent.com/assets/9104795/7907116/ca2f9c86-0867-11e5-8e6d-d1b7b15175ce.png)
![c 8bvye 5w61 f58nn0cpy5](https://cloud.githubusercontent.com/assets/9104795/7907182/dadb1e06-0868-11e5-8abd-3fe0e8ddb7dc.png)

**Comment by antinucleon** [comment]
`=` is implmented by `Saver` https://github.com/dmlc/mshadow/blob/master/mshadow/base.h#L220， https://github.com/dmlc/mshadow/blob/master/mshadow/tensor.h#L359
or just point to the data:
https://github.com/dmlc/mshadow/blob/master/mshadow/tensor.h#L351

As `[]` will return a Tensor:
https://github.com/dmlc/mshadow/blob/master/mshadow/tensor.h#L332

In that case, you need call "assign exp". The args should be an expression. My dirty solution is:

```
for (index_t i = 0; i < 3; i++){
    Tensor<cpu, 2> tmp1 = tc3[i];
    const Tensor<cpu, 2> &tmp2 = tc2;
    tmp1 = tmp2 * 1.0;
  }
```

Better solution should wait Tianqi to answer.

**Comment by superzrx** [comment]
@antinucleon 
Thank you for the answer.
May I ask two more questions ?
The first is about the difference on time cost and memory cost between your solution and Copy function. 
The second is ' is it OK to use '

``` c++
nodes_in[0]->data = nodes_out[0]->data
```

**Comment by antinucleon** [comment]
There is no memory allocation for creating new Tensor, and CPU mshadow MapperSaver engine is an run rolled double for loop, so I think the speed should be similar.

**Comment by tqchen** [comment]
The assign of mshadow is overloaded by assigning pointer reference instead of copy memory over. So
if we really want to do a data copy. Use mshadow::Copy, or 

``` c++
dst = F<op::identity>(src)
```
