### ISSUE TITLE
compile errors on dot towards TensorContainer

### ISSUE THREAD

**Issue by zhangmeishan** [dmlc/mshadow#34]
I add the following codes in basic.cpp to have a test, but it reports a compile  error for me? Do I miss something? Thanks.

TensorContainer<cpu, 2, float> matc1(Shape2(2,3));
  matc1[0]=2; matc1[1]=3;
  matc1 = 1 / matc1;

  TensorContainer<cpu, 2, float> matc2(Shape2(3,2));
  matc2[0]=1; matc2[1]=2; matc2[2]=3;

  // error: conversion from ‘mshadow::expr::DotExp<mshadow::Tensor<mshadow::cpu, 2, float>, 
  // mshadow::Tensor<mshadow::cpu, 2, float>, false, false, float>’ to non-scalar type 
  // ‘mshadow::TensorContainer<mshadow::cpu, 2, float>’ requested
  TensorContainer<cpu, 2, float> matc3 = dot(matc1, matc2);

  for (index_t i = 0; i < matc3.size(0); ++i) {
    for (index_t j = 0; j < matc3.size(1); ++j) {
      printf("%.2f ", matc3[i][j]);
    }
    printf("\n");
  }
  printf("\n");

**Comment by tqchen** [comment]
mshadow require pre-allocate the space of tensor before assigning. In your case, mat3 needs to be pre-allocated in the target shape, before you run the dot operation

**Comment by zhangmeishan** [comment]
I still have an error on compile, but on my own project that includes your code, and do not know why it happens?
error: ‘kBetaBLAS’ is not a member of ‘mshadow::sv::plusto’
The error occurs on the  dot(a, b).
Could you give me some suggestions?
Thanks very much.

**Comment by zhangmeishan** [comment]
I find the reason. I guess that dot operation may not support  vector-style Tensor<xpu, 1> in mshadow:)

**Comment by tqchen** [comment]
Thanks for reporting this. This appears to be a problem that I overlooked when updating the package. It should not be fixed, please check again
