### ISSUE TITLE
Compile error using cuda (basic_stream.cu, mshadow::InitTensorEngine)

### ISSUE THREAD

**Issue by zhangmeishan** [dmlc/mshadow#35]
nvcc -o basic_stream -O3 --use_fast_math -ccbin g++  -Xcompiler "-Wall -O3 -I../ -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda-7.0/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0" -Xlinker "-lm -lm -lcudart -lcublas -lcurand -L/usr/local/cuda-7.0/lib64 -lcblas" basic_stream.cu
basic_stream.cu(10): error: no instance of function template "mshadow::InitTensorEngine" matches the argument list

basic_stream.cu(31): error: no instance of function template "mshadow::ShutdownTensorEngine" matches the argument list

**Comment by tqchen** [comment]
init tensor stream now comes with device type template, i have updated the example. sorry for the problem
