### ISSUE TITLE
Is Mshadow Cpp_version Theano?

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [dmlc/mshadow#37]
I am currently using Mshadow to develop some NN learning tools from scratch.

And I wonder can I use Mshadow as a CPP Version of Theano?

I mean, nearly all the things that Theano is able to do, Mshadow can do them (faster on running and slower on coding) too in a similar way.

Is that correct?

**Comment by tqchen** [comment]
mshadow is not theano, in a sense that it do not provide the math compilation and autodiff functionality. It is a more low level version of matrix tensor library that allows you to write expressions and directly compiles kernel for you statically. But such level of abstraction allows you to write high level expression while being efficient enough

There is an ongoing project [mxnet](https://github.com/dmlc/mxnet) which will provide more high level features.

**Comment by zhangchen-qinyinghua** [comment]
Thank you for your reply.

**Comment by zhangchen-qinyinghua** [comment]
I just want to ask,

Do you think it is necessary for Mshadow to have the ability to do autodiff, as Theano does?
Is there any plan to make a autodiff function for Mshadow? Or is there any such plan for Mxnet?
Or is there any tools written in CPP/C can do autodiff and can be used along with Mshadow?

Thank you~

**Comment by tqchen** [comment]
This is explained in the previous answer. The requirement of efficiency in kernel compile requires mshadow to stay low level. The high level goal is planed on mxnet

**Comment by zhangchen-qinyinghua** [comment]
Thank you again!
