### ISSUE TITLE
[RFC] Deprecate mshadow and donate code to apache-mxnet

### ISSUE THREAD

**Issue by szha** [dmlc/mshadow#373]
Hi,

I'd like to propose that we move the development of mshadow to mxnet for the following reasons:
- To the best of my knowledge, mshadow is only used in mxnet.
- Many operators in mxnet depend on mshadow, so making the code base available in mxnet will ease the development process there.

In order for the IP clearance process in Apache to complete, we need the contributors of this repository to sign ICLA for mshadow for acceptance in Apache Software Foundation.

https://cla-assistant.io/dmlc/mshadow

**Comment by pengzhao-intel** [comment]
+1

**Comment by TaoLv** [comment]
What's the plan for those open issues and PRs?

**Comment by larroy** [comment]
+1 we should move PRs and issues to the MXNet repo

**Comment by tqchen** [comment]
+1, to respect the original contributions. let us keep the original commit history and do a merge like the case of MXNet.jl

**Comment by pengzhao-intel** [comment]
Will this happen in MXNet 1.5 :)

**Comment by larroy** [comment]
I don't see why not.

**Comment by larroy** [comment]
Is the vote a pass? so we can move on with the import?

**Comment by helloworld1943** [comment]
i am a newbie to these projects , will you add more tutorials to these open-source projects ? a little bit difficult for newbies

**Comment by szha** [comment]
Thanks for the pings. Though this will not be part of 1.5.0, it will be part of the release after. The tutorials for these projects are maintained in these projects so we probably won't add them to mxnet. Once mhadow is migrated we can revisit this topic and consider adding it in mxnet if it's of interest.

**Comment by szha** [comment]
Dear mshadow contributors,

In order for the IP clearance process in Apache to complete, we need the contributors of this repository to sign ICLA for mshadow for acceptance in Apache Software Foundation. If you have already signed the Apache ICLA, feel free to ignore this message. For your convenience, you can use this link to sign the ICLA https://cla-assistant.io/dmlc/mshadow.

Let me know if you have any questions. Thank you.

cc all mshadow contributors:
@DickJC123, @DrustZ, @Godricly, @Harmonicahappy, @KellenSunderland, @Lorrainexun, @TaoLv, @ZihengJiang, @alextnewman, @antoine-wdg-rmz, @ap-hynninen, @arcadiaphy, @arikpoz, @asitstands, @asmushetzel, @azai91, @cbalioglu, @cjolivier01, @eric-haibin-lin, @forwchen, @glingyan, @happynear, @hjk41, @jason-xuan, @jermainewang, @jpauwels, @kaleidoscopical, @kdavis-mozilla, @korneil, @lebeg, @leezu, @lgarithm, @loveisp, @maxint, @milandesai, @mwbyeon, @mzhang001, @pluskid, @ptrendx, @qiaohaijun, @rahul003, @reminisce, @reyoung, @sbodenstein, @shiyangdaisy23, @siemanko, @stefanhenneking, @szha, @tdomhan, @thirdwing

**Comment by szha** [comment]
@tornadomeet, @vchuravy, @xianyi, @xingmingjie, @xinyu-intel, @yinghu5, @yllan, @yupbank, @yzhliu, @zhangchen-qinyinghua, @zhenlinluo, @zhreshold

**Comment by hjk41** [comment]
just signed. sorry about the delay

**Comment by szha** [comment]
Thanks all for the help!
