### ISSUE TITLE
incorrect flag checking for -std=c++0x ?

### ISSUE THREAD

**Issue by rustandruin** [dmlc/mshadow#4]
Using gcc v. 4.6.3, I found that I needed to change the flag check from
__GXX_EXPERIMENTAL_CXX0X
to
__GXX_EXPERIMENTAL_CXX0X__
in tensor_base.h
in order to detect the -std=c++0x flag correctly.

(I was using lambdas in my code, so needed to add -std=c++0x to the compiler options, but then I got errors about not using constexpr, which is what that flag check in tensor_base.h is supposed to do ... so it looks like you need to add those underscores to get the flag check to work).

**Comment by tqchen** [comment]
Thanks for pointing that out. Indeed we didn't fully test compilation on cxx0x. 
 I am adding both check flags now(in case another one is used elsewhere).
