### ISSUE TITLE
The usage of concat

### ISSUE THREAD

**Issue by DrustZ** [dmlc/mshadow#41]
Hi , @tqchen @antinucleon ,
I notice there's a function `concat` in mshadow, AWESOME.
But how to use it? I find the function's parameter is LVALUE, RVALUE, but how can I define which dimension to concat?

**Comment by tqchen** [comment]
It is specified by the template parameter

**Comment by antinucleon** [comment]
Please refer : https://github.com/dmlc/cxxnet/blob/master/src/layer/concat_layer-inl.hpp

**Comment by DrustZ** [comment]
Thanks!

**Comment by DrustZ** [comment]
Sorry to bother, but what's the return shape of concat?
for example, if I want to concat the channel dimension of two mshadows S1(n, c1, h, w) and S2(n, c2, h, w)
producing S3(n, c1+c2, h, w), how can I do that?
`S3 = concat<2>(s1,s2)`
I assign the result to a mshadow (n, c1+c2, h, w), but the error is 
`shape of tensors are not consistent with target`.
@tqchen @antinucleon

**Comment by tqchen** [comment]
mshadow uses 0 based indexing, so do concat<1>

**Comment by DrustZ** [comment]
thanks! @tqchen  You are a life saver. 
May I ask one more question.
I assign the result to a new variable tensor(shape4(n,c1+c2,h,w))
but this causes a segmentation fault(seems like tensor won't allocate its memory  automatically).
But I can't use a `TensorContainer`variable for there's no cast for `tensor` to `TensorContainer`
What if I want to assign a tensor to a container?

**Comment by tqchen** [comment]
you can use tensorcontainer, do resize beforehand, and assign any tensor expression to it, it will behave like a tensor because it inheritate from tensor

**Comment by DrustZ** [comment]
Can't appreciate more.

**Comment by chaoids** [comment]
Hi, @tqchen @antinucleon ,
Sorry to bother, but it looks like "concat" only support 4-dimensional tensor, so is there a function to concat, say, 2-dimensional tensors? Thanks!!
