### ISSUE TITLE
Confusion about stream

### ISSUE THREAD

**Issue by DrustZ** [dmlc/mshadow#42]
Hey, I'm working on editing`backward` and`forward` functions of [guide/convnet.cu](https://github.com/dmlc/mshadow/blob/master/guide/neuralnet/convnet.cu)
As I writing the functions, I notice that the initial version of the `.cu` has two temp `TensorContainer`s : `tmp_col` and `tmp_dst`. In my completion, I need more temp Containers, so I just imitate the code and add more `TensorContainer`s like `TensorContainer<xpu, 4, real_t> tmp41, tmp42, tmp43, tmp44;
`, and in the init-function set their stream. 
But when I use them in the `forward` and `bacward` , I just can't use `-gpu` option, the output is

```
Default GPU stream was used when MSHADOW_FORCE_STREAM was on
```

In the function I `Resize` the temp Containers and assign them to some return value like `swapaxis` or `unpack_patch2col`, I debugged the process, and find when I assign them to a return value, the error happens.

And , I'm little confused about `stream`. It is used to store the operation process, right? My concept about stream is poor.
@antinucleon @tqchen 
Thank you.

**Comment by DrustZ** [comment]
The code is like (in function)

```
    tmp4d.Resize(Shape4(w,x,y,z));
//Error happens
    tmp4d = swapaxis<1,0>(reshape(tmp2d, Shape4(w,x,y,z)));
```

**Comment by winstywang** [comment]
You need to set stream for the TensorContainers as in https://github.com/dmlc/mshadow/blob/master/guide/neuralnet/convnet.cu#L46

**Comment by DrustZ** [comment]
Thanks, but I've set the stream.

**Comment by zhangchen-qinyinghua** [comment]
@DrustZ 

Just in case,
didn't you forget to init the tensor engine?

**Comment by DrustZ** [comment]
@zhangchen-qinyinghua 
what do you mean?
the stream setting is in the construct function.

**Comment by zhangchen-qinyinghua** [comment]
@DrustZ 
I mean,

InitTensorEngine<gpu>();

Once I got the same error output, just because I forgot to init the tensor engine.

Also, following two behaviors:
-forget to set the stream
-accidentally change the GPU memory by hand

seems to give the same output.

**Comment by DrustZ** [comment]
@zhangchen-qinyinghua 
But in the sample .cu(the convnet.cu), there seems no InitTensorEngine() function?
Thanks~

**Comment by zhangchen-qinyinghua** [comment]
@DrustZ 

No?

https://github.com/dmlc/mshadow/blob/master/guide/neuralnet/convnet.cu#L224

By the way, if you use GPU, you don't need to init the engine.

**Comment by DrustZ** [comment]
@zhangchen-qinyinghua
Sorry, I ignored it.
So this seems not the init fault.
I just added some containers and set their stream after other containers...
Yes, I use the GPU.

**Comment by DrustZ** [comment]
It works now. I think there's some different between ''='' and `Copy()`

**Comment by tqchen** [comment]
Yes, the = operator means tensor pointer copy in mshadow, so it is the only place you need to be careful about
