### ISSUE TITLE
How to assign one tensorContainer to a bigger one?

### ISSUE THREAD

**Issue by DrustZ** [dmlc/mshadow#43]
Say I have a `TensorContainer` C1 whose shape is (2, 3), and another `TensorContainer` C2 whose shape is (4,3) (bigger), can I assign C1 to C2's particular highest dimensions?
I tried C2.Slice(1,3) = C1, which proved vain.
@antinucleon @tqchen

**Comment by zhangchen-qinyinghua** [comment]
I think you should use copy, as following shows:

...//C1 and C2 is alloced well
mshadow::Tensor<DEVICE,2> temp=C2.Slice(1,3);
mshadow::Copy(temp,C1,C2.stream_);

I edited it.
The above codes just work.

**Comment by DrustZ** [comment]
thanks.
