### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by loveisp** [dmlc/mshadow#54]
In https://github.com/dmlc/mshadow/tree/master/guide
"for (index_t j = 0; j < ts.size(1), ++j)"
should be
"for (index_t j = 0; j < ts.size(1); ++j)".

**Comment by tqchen** [comment]
Hmm, I did not see difference in your post. Maybe consider submit a PR to this?

**Comment by loveisp** [comment]
OK. Submitted.

**Comment by tqchen** [comment]
Oh, now I find out, Thanks for the catch!

**Comment by loveisp** [comment]
np:)
