### ISSUE TITLE
A single space, a BUG?

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [dmlc/mshadow#93]
Check the code here,

https://github.com/dmlc/mshadow/blob/master/mshadow/tensor_blob.h#L320

is different from code here,

https://github.com/dmlc/mshadow/blob/master/mshadow/tensor_cpu-inl.h#L40

there is a small space after the comma.
I think that will give rise to some troubles.

For example, if I use:

```
TShape shape=mshadow::Shape2(5,5);
std::stringstream ss;
string s;
ss<<shape;
ss>>s;
//s is (5,
```

**Comment by zhangchen-qinyinghua** [comment]
It's not big deal, but will make some behaviors confusing.

**Comment by tqchen** [comment]
oh, thanks for pointing this out, let us make it consistent, can you submit a pr?

**Comment by zhangchen-qinyinghua** [comment]
@tqchen 
Sure, I am glad to.
